#ifndef PHI_MOMENTUM_SCALE_2025_TO_2026_H
#define PHI_MOMENTUM_SCALE_2025_TO_2026_H

// Generated by CalibratePhiMomentumScaleVsPt.C
// epsilon is applied to both kaon three-momenta of a phi candidate:
//   p_corr = (1 + epsilon) * p_2025
// Recalculate each kaon energy using the fixed kaon mass afterwards.

namespace PhiMomentumScale2025To2026 {
constexpr int kNBins = 14;
constexpr double kPtEdges[kNBins + 1] = {0.5, 0.8, 1.2, 1.6, 2, 2.5, 3, 4, 5, 6, 8, 10, 12, 15, 20};
constexpr double kEpsilon[kNBins] = {0.00235466554792, 0.00766063845958, 0.00817433159155, 0.00979210081761, 0.0106772751784, 0.0112900946203, 0.0115851772474, 0.0117659107172, 0.0124476672176, 0.0120879368505, 0.012370719542, 0.0143003188846, 0.0153663808091, 0.0174137228531};
constexpr bool kValid[kNBins] = {true, true, true, true, true, true, true, true, true, true, true, true, true, true};

inline double Epsilon(double reconstructedPhiPt)
{
  for (int i = 0; i < kNBins; ++i) {
    if (reconstructedPhiPt >= kPtEdges[i] &&
        reconstructedPhiPt < kPtEdges[i + 1])
      return kValid[i] ? kEpsilon[i] : 0.0;
  }
  return 0.0; // no extrapolation outside the calibrated range
}

inline double ScaleFactor(double reconstructedPhiPt)
{
  return 1.0 + Epsilon(reconstructedPhiPt);
}
} // namespace PhiMomentumScale2025To2026

#endif
