#ifndef PHI_MOMENTUM_SCALE_2025_TO_2026_H
#define PHI_MOMENTUM_SCALE_2025_TO_2026_H

// Generated by CalibratePhiMomentumScaleVsPt.C
// epsilon is applied to both kaon three-momenta of a phi candidate:
//   p_corr = (1 + epsilon) * p_2025
// Recalculate each kaon energy using the fixed kaon mass afterwards.

namespace PhiMomentumScale2025To2026 {
constexpr int kNBins = 15;
constexpr double kPtEdges[kNBins + 1] = {0.5, 0.8, 1.2, 1.6, 2, 2.5, 3, 4, 5, 6, 8, 10, 12, 15, 20, 30};
constexpr double kEpsilon[kNBins] = {0.0024146539379, 0.00762912304405, 0.00817386742107, 0.00982766792836, 0.0106788436324, 0.0112954252224, 0.0115583787246, 0.0117416086153, 0.012422150094, 0.011968584565, 0.0125561781092, 0.0139372556405, 0.014995530318, 0.0165687496159, 0.0143175890856};
constexpr bool kValid[kNBins] = {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true};

inline double Epsilon(double reconstructedPhiPt)
{
  for (int i = 0; i < kNBins; ++i) {
    if (reconstructedPhiPt >= kPtEdges[i] &&
        reconstructedPhiPt < kPtEdges[i + 1])
      return kValid[i] ? kEpsilon[i] : 0.0;
  }
  return 0.0; // no extrapolation outside the calibrated range
}

inline double ScaleFactor(double reconstructedPhiPt)
{
  return 1.0 + Epsilon(reconstructedPhiPt);
}
} // namespace PhiMomentumScale2025To2026

#endif
