#ifndef PHI_MOMENTUM_SCALE_2025_TO_2026_H
#define PHI_MOMENTUM_SCALE_2025_TO_2026_H

// Generated by CalibratePhiMomentumScaleVsPt.C
// epsilon is applied to both kaon three-momenta of a phi candidate:
//   p_corr = (1 + epsilon) * p_2025
// Recalculate each kaon energy using the fixed kaon mass afterwards.

namespace PhiMomentumScale2025To2026 {
constexpr int kNBins = 17;
constexpr double kPtEdges[kNBins + 1] = {0.8, 1, 1.2, 1.6, 2, 2.5, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 20};
constexpr double kEpsilon[kNBins] = {0.0082316288136, 0.0084477004712, 0.00919943176938, 0.0108425754669, 0.0117196805635, 0.0123951594009, 0.0123680092232, 0.0124683175364, 0.0126507831441, 0.0124286969418, 0.0123413824165, 0.0134753484815, 0.0150030728106, 0.014280642284, 0.0149542169164, 0.0174764570162, 0.0196359204232};
constexpr bool kValid[kNBins] = {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true};

inline double Epsilon(double reconstructedPhiPt)
{
  for (int i = 0; i < kNBins; ++i) {
    if (reconstructedPhiPt >= kPtEdges[i] &&
        reconstructedPhiPt < kPtEdges[i + 1])
      return kValid[i] ? kEpsilon[i] : 0.0;
  }
  return 0.0; // no extrapolation outside the calibrated range
}

inline double ScaleFactor(double reconstructedPhiPt)
{
  return 1.0 + Epsilon(reconstructedPhiPt);
}
} // namespace PhiMomentumScale2025To2026

#endif
